### ISSUE TITLE
Checklist: post_challenge_locations.csv data file format

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#10]
# Requirements for the post_challenge_locations.csv data file format
Per [page 35](https://www.ntia.gov/sites/default/files/2023-11/bead_challenge_process_policy_notice.pdf#page=35) of the policy notice and Notices of Changes to the process.

## Column Names, Order, and Data Types (dtypes):
1. `location_id` (dtype: int)
    - test: [test_post_challenge_location_column_dtypes__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/c177ecfdf372c6845b9469b55d23e4b7df692ee6/tests/test_bead_inspector/test_validator.py#L4363C5-L4363C60)
2. `classification` (dtype: int)
    - test: [test_post_challenge_location_column_dtypes__classification](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/c177ecfdf372c6845b9469b55d23e4b7df692ee6/tests/test_bead_inspector/test_validator.py#L4395C5-L4395C63)

- [ ] Correct column names
    - test: 
- [ ] Correct column order
    - test: 

## Column Content Requirements
- [x] `location_id`: Must be A 10 digit integer $\ge 10^9$ and $\lt 10^{10}$.
    - test: [test_post_challenge_location_col_content__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/c177ecfdf372c6845b9469b55d23e4b7df692ee6/tests/test_bead_inspector/test_validator.py#L4428C5-L4428C58)
- [x] `classification`: Must be in [0, 1, 2] (ie a key in this classification code-to-description map `{0: "Unserved", 1: "Underserved", 2: "Served"}`)
    - test: [test_post_challenge_location_col_content__classification](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/c177ecfdf372c6845b9469b55d23e4b7df692ee6/tests/test_bead_inspector/test_validator.py#L4463C5-L4463C61)

## Columns that can be Conditionally Null
N/A

# Multi-File Column Rules
- [ ] All `location_id`s in this should be in `challenges.csv`

## Intentionally noted but not checked by this project
* `location_id`: Must be in the Fabric for that state or territory.
