### ISSUE TITLE
Checklist: cai_challenges.csv data file format

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#11]
# Requirements for the challenges.csv data file format
Per [page 32](https://www.ntia.gov/sites/default/files/2023-11/bead_challenge_process_policy_notice.pdf#page=32) of the policy notice and Notices of Changes to the process.

## Column Names, Order, and Data Types (dtypes):
1. `challenge` (dtype: string)
2. `challenge_type` (dtype: string)
3. `challenger` (dtype: string)
4. `category_code` (dtype: string)
5. `disposition` (dtype: string)
6. `challenge_explanation` (dtype: string)
7. `type` (dtype: string)
8. `entity_name` (dtype: string)
9. `entity_number` (dtype: integer)
    - [x] test: [test_cai_challenges_column_dtypes__entity_number](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3722C5-L3722C53)
10. `cms_number` (dtype: string)
11. `frn` (dtype: string)
12. `location_id` (dtype: integer)
    - [x] test: [test_cai_challenges_column_dtypes__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3758C5-L3758C51)
13. `address_primary` (dtype: string)
14. `city` (dtype: string)
15. `state` (dtype: string)
16. `zip_code` (dtype: string)
17. `longitude` (dtype: string)
18. `latitude` (dtype: string)
19. `explanation` (dtype: string)
20. `need` (dtype: integer)
    - [x] test: [test_cai_challenges_column_dtypes__need](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3794C5-L3794C44)
21. `availability` (dtype: integer)
    - [x] test: [test_cai_challenges_column_dtypes__availability](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3832C5-L3832C52)

- [x] Correct column names
    - [x] test: [test_cai_challenges__column_names](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3624C5-L3624C38)
- [x] Correct column order
    - [x] test: [test_cai_challenges__column_order](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3655C5-L3655C38)

## Column Content Requirements
- [x] `challenge`: String with a length between (inclusive) 1 and 50 characters.
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_ChallengeIdValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L9C5-L9C30)
- [x] `challenge_type`: Enum; must be in [C, G, Q, R]
    - [x] test: [test_cai_challenges_col_content__challenge_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3870C5-L3870C52)
    - [x] test: [test_CAIChallengeType](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L51C5-L51C26)
- [x] `category_code`: Enum; must be in [X, B, R, D, N, I, T, O]
    - test: (ToDo: implement data_format-specific test and add link)
    - test: [test_CAIRationaleNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L290C5-L290C39)
- [x] `disposition`: Enum; must be in [I, N, A, S, R, M]
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [ ] test: (ToDo: implement test of constants.DispositionsOfCAIChallenge and add link)
- [x] `type`: Enum; must be in [S, L, G, H, F, P, C]
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_CAIType_validator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L301C5-L301C27)

- [x] `location_id`: A 10 digit integer $\ge 10^9$ and $\lt 10^{10}$.
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_BSLLocationIdNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L206C5-L206C40)
- [x] `state`: Enum; a 2 letter state identifier
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [ ] test: [test_State_validator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L348C5-L348C25)
- [x] `zip_code`: A zero-padded string of exactly 5 digits.
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_ZipNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L278C5-L278C30)
- [x] `longitude`: CRS = EPSG 4326 (aka WGS-84, unprojected and in degrees). Minimal precision of 6 decimal places. (Note: CRS not checked)
    - [x] test: [test_cai_challenges_col_content__longitude](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L3951C5-L3951C47)
    - [ ] test: (ToDo: implement test of constants.LongitudeNullableValidator and add link)
- [x] `latitude`: CRS = EPSG 4326 (aka WGS-84, unprojected and in degrees). Minimal precision of 6 decimal places. (Note: CRS not checked)
    - [x] test: [test_cai_challenges_col_content__latitude](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4000C5-L4000C46)
    - [ ] test: (ToDo: implement test of constants.LatitudeNullableValidator and add link)
-[x] `need`: Non-negative integer in the reasonable range for a download speed (in Mbps). I think this is 1000 Mbps for every CAI, but if that's correct, I don't know why it would be required.
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [ ] test: [test_NonNegativeNumberValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L220C5-L220C36)
- [x] `availability`: Non-negative integer in the reasonable range for an upload speed (in Mbps).
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_NonNegativeNumberValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L220C5-L220C36)

### Optional
- [x] `CMS number`: Should identify a healthcare practice (As best I can tell from google, these are 6 or 10 digit numbers, or maybe 13 digits?)
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_CMSCertificateNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L312C5-L312C41)
- [x] `frn`: FCC registration number, 10 digits, uniquely identifies registrant with FCC.
    - [ ] test: (ToDo: implement data_format-specific test and add link)
    - [x] test: [test_FrnNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_constants.py#L334C5-L334C30)

## Columns that can be Conditionally Null (and other row-rule checks)
- [x] `category_code`: Cannot be null if `type` is in [C, G, R]
    - [x] test: [test_cai_challenges_row_rule__category_code_given_challenge_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4051C5-L4051C69)
- [x] `challenge_explanation`: Cannot be null if `type` is in [C, R]
    - [x] test: [test_cai_challenge_row_rule__challenge_explanation_given_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4230C5-L4230C66)
- [x] `entity_name`: Can only be null when `type` is in [P]
    - [x] test: [test_cai_challenge_row_rule__entity_name_given_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4186C5-L4186C56)
- [x] `location_id`: Can only be null if (`address_primary`, `city`, `zip_code`) are all not null, or if (`latitude`, `longitude`) are both not null.
- [x] `address_primary`: Can only be null if `location_id` is not null, or if (`latitude`, `longitude`) are both not null.
    - [x] test: [test_cai_challenge_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4143C5-L4143C64)
- [x] `city`: Can only be null if `location_id` is not null, or if (`latitude`, `longitude`) are both not null.
    - [x] test: [test_cai_challenge_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4143C5-L4143C64)
- [x] `zip_code`: Can only be null if `location_id` is not null, or if (`latitude`, `longitude`) are both not null.
    - [x] test: [test_cai_challenge_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4143C5-L4143C64)
- [x] `longitude`: Can only be null if `location_id` is not null, or if (`address_primary`, `city`, `zip_code`) are all not null.
    - [x] test: [test_cai_challenge_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4143C5-L4143C64)
- [x] `latitude`: Can only be null if `location_id` is not null, or if (`address_primary`, `city`, `zip_code`) are all not null.
    - [x] test: [test_cai_challenge_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4143C5-L4143C64)
- [x] `explanation`: Cannot be null if `type` is in [C]
    - [x] [test_cai_challenges_row_rule__explanation_given_challenge_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4105C5-L4105C67)

### Optional
- [x] `CMS number`: Cannot be null when `type` is in [H] (maybe optional?)
    - [x] test: [test_cai_challenge_row_rule__cms_number_given_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4268C5-L4268C55)
- [x] `frn`: Cannot be null when `type` is in [S, L, H] 
    - [x] test: [test_cai_challenge_row_rule__frn_given_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L4313C5-L4313C48)

## Multi-File Requirements
- [x] `challenger`: Must uniquely identify exactly one challenger in the challenger.csv table.
    - [x] test: [test_multi_file_validations__cai_challenges_and_challengers](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/508081106f0c3800d363dde08160ebe709c83991/tests/test_bead_inspector/test_validator.py#L524C5-L524C64)
- [ ] All CAIs in `cai_challenges.csv` should either also be in `cai.csv` (i.e., it was initially identified as a CAI) or should have `challenge_type` = C (i.e., the challenge identifies this as a CAI missing from the CAI-list).

### Intentionally noted but not checked by this project
* `challenge`: Must be unique to a challenge (noted, content not validated beyond type and nullness)
* `CMS number`: Should be valid and maybe turn up in Medicare lookup tools that allow for search by CNN?
* `frn`: Should be valid and in the FCC's systems.
* `location_id`: Must be in the Fabric for that state.
* `entity_number`: "Mandatory if CAI participates in E-Rate program. Leave empty for CAIs that are neither `type` S nor L and do not participate in the E-Rate program."
