### ISSUE TITLE
Checklist: challengers.csv data file format

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#3]
# Requirements for the challengers.csv data file format
Per [page 26](https://www.ntia.gov/sites/default/files/2023-11/bead_challenge_process_policy_notice.pdf#page=26) of the policy notice and Notices of Changes to the process.

## Column Names and Order:
1. challenger
2. category
3. organization
4. webpage
5. provider_id
6. contact_name
7. contact_email
8. contact_phone

- [x] Correct column names
    - test: [test_challenger__column_names](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L144)
- [ ] Correct column order 

## Column Data Types and Content Requirements
- [x] `challenger` (dtype: string): required not null.
    - test: [test_challenger_col_content__challenger](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/main/tests/test_bead_inspector/test_validator.py#L175)
- [x] `category`: (dtype: Enum in [B, L, N, T], i.e. single-char string), required not null.
    - test: [test_challenger_col_content__category](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L205)
- [x] `organization`: (dtype: string), required not null.
    - test: [test_challenger_col_content__organization](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L240)
- [x] `webpage`: optional; should look like a URL if not null.
    - test: [test_challenger_col_content__webpage](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L272)
- [x] `provider_id`: (dtype: string) If not null, must be a six digit integer.
    - test: [test_challenger_col_content__provider_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L306)
- [x] `contact_name`: should look like a full name, required not null.
    - test: [test_challenger_col_content__contact_name](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L341)
- [x] `contact_email`: should look like an email address, required not null.
    - test: [test_challenger_col_content__contact_email](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L371)
- [x] `contact_phone`: optional; must match the pattern ddd-ddd-dddd if not null.
    - test: [test_challenger_col_content__contact_phone](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L403)

## Columns Required to be Not Null
* [`challenger`, `category`, `organization`, `provider_id`, `contact_name`,  `contact_email`]
- [x] Check that these aren't blank or null

## Columns that can be Conditionally Null
- [x] `provider_id`: Can only be null if `category` is not "B"
    - test: [test_challenger_row_rule__ISPs_need_provider_ids](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L438)

# Multi-File Column Rules

## Intentionally noted but not checked by this project
* `provider_id`: must match a `provider_id` in the FCC's `provider_id` list.
