### ISSUE TITLE
Checklist: challenges.csv data file format

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#4]
# Requirements for the challengers.csv data file format
Per [page 27](https://www.ntia.gov/sites/default/files/2023-11/bead_challenge_process_policy_notice.pdf#page=27) of the policy notice and Notices of Changes to the process.

## Column Names, Order, and Data Types (dtypes):
1. `challenge` (dtype: string)
2. `challenge_type` (dtype: single-character string)
3. `challenger` (dtype: string)
4. `challenge_date` (dtype: string)
5. `rebuttal_date` (dtype: string)
6. `resolution_date` (dtype: string)
7. `disposition` (dtype: single-character string)
8. `provider_id` (dtype: integer here, string in challenger)
9. `technology` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__technology](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L619)
11. `location_id` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L664)
12. `unit` (dtype: string)
13. `reason_code` (dtype: single-character string)
14. `evidence_file_id` (dtype: string)
15. `response_file_id` (dtype: string)
16. `resolution` (dtype: string)
17. `advertised_download_speed` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__advertised_download_speed](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L702)
18. `download_speed` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__download_speed](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L739) 
20. `advertised_upload_speed` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__advertised_upload_speed](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L777)
22. `upload_speed` (dtype: integer)
    * dtype test: [test_challenges_column_dtypes__upload_speed](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L815) 
24. `latency` (dtype: float)
    * dtype test: [test_challenges_column_dtypes__latency](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L853) 

- [x] Correct column names
    - test: [test_challenges__column_names](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L476)
- [x] Correct column order
    - test: [test_challenges__column_order](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L516) 

## Column Content Requirements
- [x] `challenge`: String with a length between (inclusive) 1 and 50 characters.
    - test: [test_challenges_col_content__challenge](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L891) 
- [x] `challenge_type`: Enum in [A, S, L, D, T, B, P, E, N, V, F, M, X, Y, Z]
    - test: [test_challenges_col_content__challenge_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L930)
- [x] `challenge_date`:
    - [x] Must be in ISO 8601 extended date format.
        - test: [test_challenges_col_content__challenge_date](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L988)
    - [x] Must precede other dates (if they're not null) 
        - test: [test_challenges_row_rule__rebuttal_date_not_before_challenge_date](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L1953)
        - test: [test_challenges_row_rule__resolution_date_not_before_challenge_date](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/35d279c8444d92ca6dbdbb1e472e71d382674812/tests/test_bead_inspector/test_validator.py#L1991) 

- `rebuttal_date`:
    - [x] Must be in ISO 8601 extended date format.
    - [x] Must be later than challenge date and before or on resolution date.
- `resolution_date`:
    - [x] Must be in ISO 8601 extended date format.
    - [x] Must be later than challenge date and on or after rebuttal_date.

## Columns that can be Conditionally Null

# Multi-File Column Rules

## Intentionally noted but not checked by this project
* `provider_id`: Must be a valid provider in the state.
* `location_id`: Must be in the Fabric for that state.

## Conditional Nulls

- [ ] `challenger`:
    - [x] null for `challenge_type`s [V, F, M, X, Y, and Z]
    - [ ] null if "[`challenge_type`] E or N challenge was part of pre-challenge process deduplication."
- [x] `rebuttal_date`: null if no rebuttal (`response_file_id` should also be null)
- [x] `resolution_date`: null if not resolved yet 
    * (all should be resolved at the end of the portal window)
- [x] `provider_id`: CANNOT be null for any `challenge_type` except for "P" (planned service)
- [x] `technology`: per NTIA spreadsheet: can be null if `challenge_type` is "N" (not part of an enforceable commitment)
- [x] `reason_code`: CANNOT be null if `challenge_type` is "A" (availability)
- [x] `evidence_file_id`: per NTIA spreadsheet: null if `challenge_type` is "E" or "V" (enforceable commitment or DSL)
- [x] `response_file_id`: null if no rebuttal (`rebuttal_date` should also be null)
- [x] `resolution`: NOT null for `challenge_type`s [E, I, S, R]
    - [x] "For E, include name of broadband funding program or other source of the commitment, as applicable." (per pg 30 of the policy notice)
        * I'm not sure how to check for that (yet?), but if we do want to handle that, the logic to check for such a mention goes here.
- [x]  `advertised_download_speed`:  per NTIA spreadsheet: can be null if `challenge_type` is "N" (not part of an enforceable commitment)
    * per the policy doc, it only says it's required for `challenge_type`s [A, E, L, P, S]
- [x] `download_speed`: CANNOT be null for `challenge_type`s [S, M]
- [x]  `advertised_upload_speed`:  per NTIA spreadsheet: can be null if `challenge_type` is "N" (not part of an enforceable commitment)
- [x] `upload_speed`: CANNOT be null for `challenge_type`s [S, M]
- [x] `latency`: CANNOT be null for `challenge_type`s [L, M]

# Content Requirements

## Single-File Requirements

- [x] `disposition`: Enum in [I, N, A, S, R, M]
- [x] `provider_id`: A unique 6-digit integer identifying an ISP in the FCC's providers data.
- [x] `technology`: Enum in [10, 40, 50, 60, 61, 70, 71, 72, 0]
- [x] `location_id`: a 10-digit integer $\ge 10^9$ and $\lt 10^{10}$
- [x] `reason_code`: Enum in [1, 2, 3, 4, 5, 6, 8, 9]
- [x] `evidence_file_id`: "File names for evidence and responses must only contain US ASCII letters, the digits 0-9, hyphens (-) and underscore (_) characters. File names are not case sensitive. The file name extension must be pdf (PDF files); other file types may be permitted in the future."
- [x] `response_file_id`: "File names for evidence and responses must only contain US ASCII letters, the digits 0-9, hyphens (-) and underscore (_) characters. File names are not case sensitive. The file name extension must be pdf (PDF files); other file types may be permitted in the future."
- [x] `resolution`: Free text, "required for E, I, S, and R" (presumably `challenge_type`s, but there isn't a type I and R is a CAI type)
- [x] `advertised_download_speed`: Non-negative integer, Mbps.
- [x] `download_speed`: Non-negative number, Mbps.
- [x] `advertised_upload_speed`: Non-negative integer, Mbps.
- [x] `upload_speed`: Non-negative number, Mbps.
- [x] `latency`: Non-negative number, ms.

## Multi-File Requirements:
- [x] `challenger`: Uniquely identifies a challenger in the table challenger.csv (not case sensitive)
