### ISSUE TITLE
Checklist: cai.csv and data file format

### ISSUE THREAD

**Issue by MattTriano** [uchicago-dsi/uchicago-bead-challenge-validation-tool#5]
# Requirements for the cai.csv data file format
Per [page 27](https://www.ntia.gov/sites/default/files/2023-11/bead_challenge_process_policy_notice.pdf#page=27) of the policy notice and Notices of Changes to the process.

## Column Names, Order, and Data Types (dtypes):
1. `type` (dtype: string)
2. `entity_name` (dtype: string)
3. `entity_number` (dtype: integer)
    - [x] test: [test_cai_column_dtypes__entity_number](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2440C5-L2440C42) 
4. `CMS number` (or `cms_number`) (dtype: string)
5. `frn` (dtype: string)
6. `location_id` (dtype: integer)
    - [x] test: [test_cai_column_dtypes__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2473C5-L2473C40)
7. `address_primary` (dtype: string)
8. `city` (dtype: string)
9. `state` (dtype: two-character string)
10. `zip_code` (dtype: five-character string)
11. `longitude` (dtype: float)
    - [x] test: [test_cai_column_dtypes__longitude](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2507C5-L2507C38)
12. `latitude` (dtype: float)
    - [x] test: [test_cai_column_dtypes__latitude](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2541C5-L2541C37)
13. `explanation` (dtype: string)
14. `need` (dtype: integer)
    - [x] test: [test_cai_column_dtypes__need](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2576C5-L2576C33)
15. `availability` (dtype: string)
    - [x] test: [test_cai_column_dtypes__availability](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2611C5-L2611C41)

- [x] Correct column names
    - test: [test_cai__column_names](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2349C5-L2349C27)
- [x] Correct column order
    - test: [test_cai__column_order](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2379C5-L2379C27)

## Column Content Requirements
- [x] `type`: Enum; in [S, L, G, H, F, P, C]
    - test: [test_cai_col_content__type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2646C5-L2646C31)
    - test: [test_CAIType_validator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L300C5-L300C27)
- [x] `location_id`: A 10 digit integer $\ge 10^9$ and $\lt 10^{10}$. 
   - test: [test_cai_col_content__location_id](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2795C5-L2795C38)
   - test: [test_BSLLocationIdNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L205C5-L205C40)
- [x] `state`:  Enum; a 2 letter state identifier
    - test: [test_cai_col_content__state](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2832C5-L2832C32)
    - test: [test_State_validator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L347C5-L347C25)
- [x] `zip_code`: A zero-padded string of exactly 5 digits.
    - test: [test_cai_col_content__zip_code](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2870C5-L2870C35)
    - test: [test_ZipNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L277C5-L277C30)
- [ ] `longitude`: A value reflecting the unprojected longitude (in WGS-84 CRS) in decimal degrees, with 6 decimal places of precision.
- [ ] `latitude`: A value reflecting the unprojected latitude (in WGS-84 CRS) in decimal degrees, with 6 decimal places of precision.
- [x] `need`: A positive integer reflecting the needed broadband speed (in Mbps; presumably 1000 everywhere)
    - test: [test_cai_col_content__need](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2985C5-L2985C31)
- [x] `availability`: An integer reflecting the highest speed service available at the location (in Mbps).
    - test: [test_cai_col_content__availability](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3016C5-L3016C39)

### Optional
- [x] `CMS number`: Should identify a healthcare practice (As best I can tell from google and the given links, these are 6 or 10 digit numbers)
    - test: [test_cai_col_content__cms_number](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2719C5-L2719C37)
    - test: [test_CMSCertificateNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L311C5-L311C41)
- [x] `frn`: FCC registration number, 6 or 10 digits, uniquely identifies registrant with FCC.
    - test: [test_cai_col_content__frn](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2756C5-L2756C30)
    - test: [test_FrnNullableValidator](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_constants.py#L333C5-L333C30)

## Columns Required to be Not Null
- [x] `type`: test: [test_cai_col_content__type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2646C5-L2646C31)
- [x] `entity_name`: test [test_cai_col_content__entity_name](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2688C5-L2688C38)
- [x] `state`: test: [test_cai_col_content__state](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2832C5-L2832C32)
- [x] `need`: test: [test_cai_col_content__need](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L2985C5-L2985C31)

## Columns that can be Conditionally Null
- [x] `location_id`: Can only be null if (address_primary, city, zip_code) are all not null, or if (latitude, longitude) are both not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `address_primary`: Can only be null if location_id is not null, or if (latitude, longitude) are both not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `city`: Can only be null if location_id is not null, or if (latitude, longitude) are both not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `zip_code`: Can only be null if location_id is not null, or if (latitude, longitude) are both not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `longitude`: Can only be null if location_id is not null, or if (address_primary, city, zip_code) are all not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `latitude`: Can only be null if location_id is not null, or if (address_primary, city, zip_code) are all not null.
    - test: [test_cai_row_rule__location_possibly_determinable](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3048C5-L3048C54)
- [x] `explanation`: Cannot be null if type is in [C]
    - test: [test_cai_row_rule__explanation_given_cai_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3178C5-L3178C50)

### Optional
- [x] `CMS number`: Cannot be null when `type` is in [H]
    - test: [test_cai_row_rule__cms_number_given_cai_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3089C5-L3089C49)
- [x] `frn`: Cannot be null when `type` is in [S, L, H]
    - test: [test_cai_row_rule__frn_given_cai_type](https://github.com/uchicago-dsi/uchicago-bead-challenge-validation-tool/blob/96b12a6d33e872ececc9fdf20cf76b9ed357ebad/tests/test_bead_inspector/test_validator.py#L3134C5-L3134C42)

# Multi-File Column Rules
N/A

### Intentionally noted but not checked by this project
* `entity_number`: "Mandatory if CAI participates in E-Rate program. Leave empty for CAIs that are neither type S nor L and do not participate in the E-Rate program."
* `CMS number`: Should be valid and maybe turn up in Medicare lookup tools that allow for search by CNN?
* `frn`: Should be valid and in the FCC's systems.
* `location_id`: Must be in the Fabric for that state.
